title: 跨境电商运营指南
description: 跨境电商运营完整知识体系
baseurl: "/YuanOversea"
url: "https://albertbouny.github.io"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

aux_links:
  "GitHub":
    - "https://github.com/AlbertBouny/YuanOversea"

footer_content: "Copyright &copy; 2024 跨境电商运营指南"

# Just the Docs 配置
search_enabled: true
heading_anchors: true
color_scheme: light