title: 跨境电商运营指南
description: 跨境电商运营完整知识体系
baseurl: "/YuanOversea"
url: "https://albertbouny.github.io"

# 主题设置
theme: minima

# 导航链接
header_pages:
  - docs/core/index.md
  - docs/supply-chain/index.md
  - docs/operation-support/index.md
  - docs/foundation/index.md
  - docs/compliance/index.md
  - docs/resources/index.md
  - docs/tools/index.md