title: 跨境电商运营指南
description: 跨境电商运营完整知识体系
baseurl: "/YuanOversea"
url: "https://albertbouny.github.io"

# 主题设置
theme: jekyll-theme-cayman

# 启用必要的插件
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-titles-from-headings

# 配置
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# 导航设置
aux_links:
  "GitHub 仓库":
    - "https://github.com/AlbertBouny/YuanOversea"

# 目录结构
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# 搜索配置
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false