title: 跨境电商运营指南
description: 跨境电商运营完整知识体系
baseurl: "/YuanOversea"
url: "https://albertbouny.github.io"

# 主题设置
remote_theme: just-the-docs/just-the-docs@v0.4.2

# 启用必要的插件
plugins:
  - jekyll-remote-theme

# Just the Docs 配置
search_enabled: true
heading_anchors: true
color_scheme: light

# 导航设置
aux_links:
  "GitHub 仓库":
    - "https://github.com/AlbertBouny/YuanOversea"

# 目录结构
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# 搜索配置
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false 