title: 跨境电商运营指南
description: 跨境电商运营完整知识体系
baseurl: "/YuanOversea"
url: "https://albertbouny.github.io"

# 主题设置
remote_theme: just-the-docs/just-the-docs@v0.4.2

# 启用必要的插件
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Just the Docs 配置
search_enabled: true
heading_anchors: true
color_scheme: light

# 导航排序
nav_sort: case_sensitive

# 导航结构
defaults:
  - scope:
      path: "docs/core"
    values:
      nav_order: 1
  - scope:
      path: "docs/supply-chain"
    values:
      nav_order: 2
  - scope:
      path: "docs/operation-support"
    values:
      nav_order: 3
  - scope:
      path: "docs/foundation"
    values:
      nav_order: 4
  - scope:
      path: "docs/compliance"
    values:
      nav_order: 5
  - scope:
      path: "docs/resources"
    values:
      nav_order: 6
  - scope:
      path: "docs/tools"
    values:
      nav_order: 7

# 页脚设置
footer_content: "Copyright &copy; 2024 跨境电商运营指南"

# 辅助链接
aux_links:
  "在 GitHub 上查看":
    - "https://github.com/AlbertBouny/YuanOversea"

# 搜索设置
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true