title: 跨境电商运营指南
description: 跨境电商运营完整知识体系
baseurl: "/YuanOversea"
url: "https://albertbouny.github.io"

# 主题设置
remote_theme: just-the-docs/just-the-docs@v0.4.2

# 启用必要的插件
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Just the Docs 配置
search_enabled: true
heading_anchors: true
color_scheme: light

# 导航排序
nav_sort: case_sensitive

# 导航结构
nav:
  - title: 核心业务
    url: /docs/core/
    nav_order: 1
  - title: 供应链管理
    url: /docs/supply-chain/
    nav_order: 2
  - title: 运营支持
    url: /docs/operation-support/
    nav_order: 3
  - title: 基础支撑
    url: /docs/foundation/
    nav_order: 4
  - title: 合规风控
    url: /docs/compliance/
    nav_order: 5
  - title: 资源对接
    url: /docs/resources/
    nav_order: 6
  - title: 工具模板
    url: /docs/tools/
    nav_order: 7

# 页脚设置
footer_content: "Copyright &copy; 2024 跨境电商运营指南"

# 辅助链接
aux_links:
  "在 GitHub 上查看":
    - "https://github.com/AlbertBouny/YuanOversea"

# 搜索设置
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true