title: 跨境电商运营指南
description: 跨境电商运营完整知识体系
baseurl: "/YuanOversea"
url: "https://albertbouny.github.io"
remote_theme: just-the-docs/just-the-docs
markdown: kramdown

# 启用必要的插件
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# Just the Docs 配置
search_enabled: true
heading_anchors: true
color_scheme: light

# 导航设置
aux_links:
  "GitHub 仓库":
    - "https://github.com/AlbertBouny/YuanOversea"

# 额外配置
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "docs/tests/"] 