title: 跨境电商运营指南
description: 跨境电商运营完整知识体系
baseurl: "/YuanOversea"
url: "https://albertbouny.github.io"

# 主题设置
remote_theme: just-the-docs/just-the-docs@v0.4.2

# 启用必要的插件
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Just the Docs 配置
search_enabled: true
heading_anchors: true
color_scheme: light
nav_external_links:
  - title: GitHub 仓库
    url: https://github.com/AlbertBouny/YuanOversea
    hide_icon: false

# 导航排序
nav_sort: case_sensitive

# 启用复制代码按钮
enable_copy_code_button: true

# 页脚设置
footer_content: "Copyright &copy; 2024 跨境电商运营指南. Distributed by an <a href=\"https://github.com/AlbertBouny/YuanOversea/blob/main/LICENSE\">MIT license.</a>"

# 最后修改时间
last_edit_timestamp: true
last_edit_time_format: "%Y-%m-%d %H:%M:%S"

# 辅助链接
aux_links:
  "在 GitHub 上查看":
    - "https://github.com/AlbertBouny/YuanOversea"

# 搜索设置
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true