title: 跨境电商运营指南
description: 跨境电商运营完整知识体系
baseurl: "/YuanOversea"
url: "https://albertbouny.github.io"
remote_theme: just-the-docs/just-the-docs

# 启用必要的插件
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# Just the Docs 配置
search_enabled: true
heading_anchors: true
color_scheme: light

# 导航设置
aux_links:
  "GitHub 仓库":
    - "https://github.com/AlbertBouny/YuanOversea"

# 文档设置
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation 