title: 跨境电商运营指南
description: 跨境电商运营完整知识体系
baseurl: "/YuanOversea"
url: "https://albertbouny.github.io"

# 主题设置
theme: jekyll-theme-primer
remote_theme: just-the-docs/just-the-docs

# 启用必要的插件
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# Just the Docs 配置
search_enabled: true
heading_anchors: true
color_scheme: light

# 导航设置
aux_links:
  "GitHub 仓库":
    - "https://github.com/AlbertBouny/YuanOversea"

# 目录显示配置
nav:
  - title: 核心业务
    children:
      - title: Temu运营
        url: /docs/core/temu/
      - title: 亚马逊运营
        url: /docs/core/amazon/
      - title: TikTok Shop运营
        url: /docs/core/tiktok/
  - title: 供应链
    url: /docs/supply-chain/
  - title: 运营支持
    url: /docs/operation/
  - title: 基础支撑
    url: /docs/foundation/
  - title: 合规风控
    url: /docs/compliance/
  - title: 资源对接
    url: /docs/resources/
  - title: 工具模板
    url: /docs/tools/

# 显示所有页面
show_all_pages: true 